### ISSUE TITLE
"rollup-plugin-visualizer" not showing the results post-optimization

### ISSUE THREAD

**Issue by wwwonka** [yushijinhun/three-minifier#10]
Hi. First of all, awesome work and thanks for sharing. It works magically once set.

Not really here for a bug, rather more for something like a feature request...
I am trying to set Rollup to show the bundle statistics properly using [rollup-plugin-visualizer](https://github.com/btd/rollup-plugin-visualizer) but it somehow fails and shows the sizes as if three-minifier never did anything. My bundled three.js file is 343kb and the visualizer shows as the following: 
<img width="1440" alt="stats" src="https://user-images.githubusercontent.com/16738328/124695695-b740ff80-deb1-11eb-825e-64bab5d24147.png">

I tried with and without sourcemaps set to true in both the output and the plugin settings but the visualizer won't display the correct results. Here is a peak at my rollup.config.js file:

```
export default {
    input: 'src/main.js',
    output: {
        file: 'build/js/main.js',
        format: 'iife',
        sourcemap: sourcemap
    },
    plugins: [
        threeMinifier(), // Must be first
        nodeResolve(),
        terser({
            ecma: 2015,
            mangle: { toplevel: true },
            compress: {
                toplevel: true,
                drop_console: !dev,
                drop_debugger: !dev
            },
            output: { quote_style: 1 }
        }),
        serve('build'),
        visualizer({
            sourcemap: true,
            gzipSize: true
        })
    ]
};
```

Is there something in the settings that you think could resolve that?

**Comment by yushijinhun** [comment]
After removing `terser` plugin, the bundle statistics seem to be correct.

![image](https://user-images.githubusercontent.com/8373027/124717631-e4d08c00-df37-11eb-9452-7d90fd82dec3.png)

```
$ ls -alh dist_experimental
total 1.5M
drwxr-xr-x 2 yushi yushi 4.0K Jul  7 14:59 .
drwxr-xr-x 5 yushi yushi 4.0K Jul  7 15:24 ..
-rw-r--r-- 1 yushi yushi 612K Jul  7 15:25 index.js
-rw-r--r-- 1 yushi yushi 892K Jul  7 15:25 index.js.map
```

I think this problem might have something to do with `rollup-plugin-teser`.

**Comment by wwwonka** [comment]
You're right! I digged around the terser documentation but haven't been able to find an option to toggle that would update the file sizes in the visualizer accordingly yet.

To generate the sourcemaps, terser must be bypassing three-minifier completely and look at the threejs files directly instead. Not sure exactly. That's too bad.

...Guessing from your screenshot, I see you've been using the visualizer plugin too.
By any chances, are you using a minifier for your project code that works with the visualizer too?

**Comment by yushijinhun** [comment]
I do not use the visualizer plugin in my projects, and currently I have no idea how to make the file sizes displayed correctly.

**Comment by wwwonka** [comment]
No worries.
