### ISSUE TITLE
Compatability with SvelteKit/Vite

### ISSUE THREAD

**Issue by drac-dot-gay** [yushijinhun/three-minifier#13]
I understand if this is a niche issue, but I'm attempting to get this plugin to work with SvelteKit. Here's my setup:

cityArt.ts:
```js
import {
    BoxGeometry, DoubleSide,
    Mesh,
    MeshBasicMaterial, OrthographicCamera,
    PlaneGeometry,
    Scene,
    WebGLRenderer
} from "three";

// .. fun scene code
```

svelte.config.js:
```js
import preprocess from 'svelte-preprocess';
import node from '@sveltejs/adapter-node';
import adapter from '@sveltejs/adapter-static';
import {threeMinifier} from "@yushijinhun/three-minifier-rollup";

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [preprocess({
        "postcss": true,
        "babel": false
    })],

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
        adapter: adapter(),
        vite: () => {
            return {
                plugins: [{...threeMinifier(), enforce: "pre"}]
            }
        }
	}
};
```

As far as i can tell, the bundle size is being reduced, possibly for whatever reason that module origins aren't being found and as a consequence not minified. I'm using `enforce: "pre"` as it seems to do the best job at covering built modules.

If you need any more info, let me know!

**Comment by enriquecastill0** [comment]
@murl-digital  Hey, im having the same issue. Did you find a way to get this to work with SvelteKit?

**Comment by drac-dot-gay** [comment]
Sadly, no. I couldn't figure out what was going on and just lived with the chonky bundles.

**Comment by yushijinhun** [comment]
@enriquecastill0 Does @murl-digital's approach work for you? It works quite well here and gives me ~30% reduce in size.
