### ISSUE TITLE
Not working with webpack 5

### ISSUE THREAD

**Issue by yushijinhun** [yushijinhun/three-minifier#8]
After upgrading webpack to 5.0.0, there is no change in bundle size.
```
Results:
Test 01_core_treeshake: webpack: 560.60K => 560.60K (-0.00, 0%)
Test 02_example_treeshake: webpack: 609.38K => 609.38K (-0.00, 0%)
Test 03_core_all: webpack: 641.00K => 641.00K (-0.00, 0%)
Test 04_example_all: webpack: 2.70M => 2.70M (-0.00, 0%)
Test 05_example_SubsurfaceScatteringShader: webpack: 562.43K => 562.43K (-0.00, 0%)
```
https://github.com/yushijinhun/three-minifier/runs/1237770797#step:6:124

**Comment by yushijinhun** [comment]
Git bisecting says that https://github.com/webpack/webpack/commit/c94073b31cb446982f22a76c1cc91fcebcac8d4d is the first bad commit.

**Comment by yushijinhun** [comment]
I did some more testing and found that https://github.com/webpack/enhanced-resolve/commit/b2ecc57852da701d3bf5a053e1d5cb3435206d3a is the commit that breaks three-minifier.

**Comment by yushijinhun** [comment]
Tree shaking works now, but source optimizing is still broken.

**Comment by yushijinhun** [comment]
> but source optimizing is still broken.

https://github.com/webpack/webpack/commit/5b4cbb5ee041bd96c80f0d657bda5f6fe5bc1450 is the first bad commit.

**Comment by edunad** [comment]
Love this package so much, I hope you can get v5 working :D

**Comment by danny-laa** [comment]
@yushijinhun Can you release the fix to npm?

It works for me, but until you do so I have to install the package from GitHub.

**Comment by yushijinhun** [comment]
> @yushijinhun Can you release the fix to npm?
> 
> It works for me, but until you do so I have to install the package from GitHub.

This bug hasn't been fixed yet as source optimizing is still broken.

**Comment by danny-laa** [comment]
@yushijinhun Consider that the current version doesn't work at all, I think it worths releasing a tree shaking only fix. It is still better than nothing.

Furthermore, it seems that there will be months before a full fix landed (the last commit was three months ago).

**Comment by yushijinhun** [comment]
@danny-laa I published 0.3.0-alpha.0. You can use this version.

**Comment by danny-laa** [comment]
Thanks 🙏🏻

**Comment by l0calh05t** [comment]
@yushijinhun I'm not observing any effect with 0.3.0-alpha.0 either. Could it be because I use three from TypeScript? Or is it the combination of WebPack 5 and TypeScript?

**Comment by hexxone** [comment]
> 
> 
> @yushijinhun I'm not observing any effect with 0.3.0-alpha.0 either. Could it be because I use three from TypeScript? Or is it the combination of WebPack 5 and TypeScript?

I am on webpack 5.27.1, with three.js and typescript without any issue. 
using "awesome-typescript-loader" in combination with "ttypescript" and "ts-transformer-properties-rename".

Here you can see how the different components now get resolved in the lower picture:
![grafik](https://user-images.githubusercontent.com/5312542/123313368-c3c86e00-d529-11eb-957b-64532bda7e2d.png)

I got from ~600kb bundle size down to about ~520kb, was already using terser before.

Now I can even see exactly which components are bundled within BundleAnalyzerPlugin :)

I will be pushing my code to my repo soon, if your problem still exists.
Cheers

**Comment by yushijinhun** [comment]
Source optimizing works now.
```
Test 01_core_treeshake: rollup: 541.22K => 337.96K (-203.26K, -37.55%)
Test 01_core_treeshake: webpack: 541.63K => 337.88K (-203.76K, -37.61%)
Test 02_example_treeshake: rollup: 590.00K => 25.47K (-564.54K, -95.68%)
Test 02_example_treeshake: webpack: 590.42K => 25.40K (-565.02K, -95.69%)
Test 03_core_all: rollup: 612.78K => 594.04K (-18.74K, -3.05%)
Test 03_core_all: webpack: 621.13K => 600.38K (-20.76K, -3.34%)
Test 04_example_all: rollup: 2.64M => 2.54M (-99.71K, -3.78%)
Test 04_example_all: webpack: 2.64M => 2.54M (-100.32K, -3.81%)
Test 05_example_SubsurfaceScatteringShader: rollup: 543.00K => 132.84K (-410.17K, -75.53%)
Test 05_example_SubsurfaceScatteringShader: webpack: 543.47K => 132.83K (-410.64K, -75.55%)
```

**Comment by yushijinhun** [comment]
Webpack 5 support is now in v0.3.0.
